services:
  webdev_database:
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - webdev_network
  webdev_server:
    build:
      dockerfile: ../dockerfile
      context: src/
    volumes:
      - ./src/:/var/www/webdev.com/
    ports:
      - 80:80
    env_file:
      - .env
    networks:
      - webdev_network
networks:
  webdev_network:
